agent any

environment {
	dockerHome = tool 'myDocker'
	mavenHome = tool 'myMaven'
	PATH = "$dockerHome/bin:$mavenHome/bin:$PATH"
}

stages{
	stage('Build'){
		steps {
			sh 'mvn --version'
			sh 'docker version'
			echo "PATH - $PATH"
			echo "JOB_NAME"
			echo "BUILD ID - $env.BUILD_ID"
		}
	}
}