 pipeline{
 agent any
	// agent {docker { image 'node:13.8'}}
	 
	 environment{
		 dockerHome = tool 'myDocker'
		// mavenHome = tool 'myMaven'
		 PATH = "$mavenHome/bin:$PATH"
	 }
stages{
	stage('details'){
		steps {
			echo "hi"
			echo "node version is"
			//sh 'node --version'
			echo "BUILD_NUMBER"
			echo "$env.BUILD_NUMBER"
			echo "BUILD_TAG"
			echo "$env.BUILD_TAG"
			sh 'mvn --version'
			//sh 'docker version'
			echo "path is"
			echo "$PATH"
			echo "this is declarative pipiline"
			}
	}
	stage('complie'){
		steps{
			sh "mvn clean compile"
		}
	}
	
	stage('test'){
		steps{
			sh "mvn test"
		}
	}
	stage('Integration Test'){
		steps{
			sh "mvn failsafe:integration-test failsafe:verify"
		}
	}
}
}
